name: unit-test
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: unit test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Environment
        uses: actions/setup-node@v3
      - name: Install Crypto SDK
        run: |
          cd smart-contract/crypto-sdk
          npm install
          npm run build
      - name: Test
        run: |
          cd smart-contract
          npm i
          npx hardhat test
